install clang-format
install cmake
install exercism
install fzf
install gh
install libevent
install luajit
install luarocks
install luv
install n
install neovim
install pandoc
install pkg-config
install python@3.9
install ripgrep
install utf8proc
install yarn
install yuicompressor
install zsh
