install bash
install clang-format
install cmake
install doctl
install exercism
install fzf
install gh
install go
install gopls
install heroku/brew/heroku
install koekeishiya/formulae/skhd
install koekeishiya/formulae/yabai
install libevent
install luajit
install luarocks
install lz4
install n
install neofetch
install neovim
install pandoc
install pkg-config
install ripgrep
install tcl-tk
install utf8proc
install wimlib
install yarn
install yuicompressor
install zsh
