#!/usr/bin/env bash

set -e

# Get Homebrew if not installed 
which -s brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install packages from Brewfile
cd homebrew && brew bundle && cd ..

# Disable Dock icon for Hammerspoon
defaults write org.hammerspoon.Hammerspoon MJShowDockIconKey -bool FALSE

# Run dotbot install script to get and link dotfile configs
./install

# Open Hammerspoon and Karabiner (keyboard setup) and enable them at startup
open /Applications/Hammerspoon.app
open /Applications/Karabiner-Elements.app

osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Hammerspoon.app", hidden:true}' > /dev/null
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Karabiner-Elements.app", hidden:true}' > /dev/null

echo "Done! Remember to enable Accessibility for Hammerspoon."

